// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGhiDanh.Data;

#nullable disable

namespace QuanLyGhiDanh.Migrations
{
    [DbContext(typeof(QuanLyGhiDanhContext))]
    [Migration("20221022024026_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyGhiDanh.Data.BoMon", b =>
                {
                    b.Property<int>("IdBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoMon"), 1L, 1);

                    b.Property<string>("BoMonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBoMon");

                    b.ToTable("BoMon");
                });

            modelBuilder.Entity("QuanLyGhiDanh.Data.GiaoVien", b =>
                {
                    b.Property<int>("IdGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiaoVien"), 1L, 1);

                    b.Property<string>("AnhDaiDienGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CacMonGiangDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaoVienName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayHopTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SDTGiaoVien")
                        .HasColumnType("int");

                    b.HasKey("IdGiaoVien");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("QuanLyGhiDanh.Data.HocVien", b =>
                {
                    b.Property<int>("IdHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocVien"), 1L, 1);

                    b.Property<string>("AnhDaiDienHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocVienName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SDTPhuHuynh")
                        .HasColumnType("int");

                    b.HasKey("IdHocVien");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("QuanLyGhiDanh.Data.KhoaHoc", b =>
                {
                    b.Property<int>("IdKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhoaHoc"), 1L, 1);

                    b.Property<int>("KhoaHocName")
                        .HasColumnType("int");

                    b.HasKey("IdKhoaHoc");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyGhiDanh.Data.LopHoc", b =>
                {
                    b.Property<int>("IdLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLopHoc"), 1L, 1);

                    b.Property<string>("GioHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocPhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLopHoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("QuanLyGhiDanh.Data.NhomBoMon", b =>
                {
                    b.Property<int>("IdNhomBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhomBoMon"), 1L, 1);

                    b.Property<string>("NhomBoMonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhomBoMon");

                    b.ToTable("NhomBoMon");
                });
#pragma warning restore 612, 618
        }
    }
}
